Manticore: overhaul 10-wait-mysql entrypoint script
Make it less verbose, but print friendly messages about progress.

diff --git a/system/docker/manticore/entrypoint.d/10-wait-mysql b/system/docker/manticore/entrypoint.d/10-wait-mysql
--- a/system/docker/manticore/entrypoint.d/10-wait-mysql
+++ b/system/docker/manticore/entrypoint.d/10-wait-mysql
@@ -1,18 +1,25 @@
 #!/bin/sh
-set -eux
+set -eu
 
-for try in $(seq 1 30); do
+tries=30
+
+for try in $(seq 1 $tries); do
   if mysqladmin status \
     --host="${MYSQL_HOST}" \
     --user="${MYSQL_USER}" \
-    --password="${MYSQL_PASSWORD}"
+    --password="${MYSQL_PASSWORD}" \
+    >/dev/null 2>&1
   then
     exit 0
   fi
 
-  sleep 5
+  if [ $try -lt $tries ]; then
+    echo "Could not connect to MySQL; trying again in 5s... (${try}/${tries})" >&2
+    sleep 5
+  fi
 done
 
+echo "Could not connect to MySQL after ${tries} attempts. Giving up." >&2
 exit 1
 
 # vim: ai ts=2 sw=2 et sts=2 ft=sh
