Manticore: name the indexes before we start building them

diff --git a/system/docker/manticore/entrypoint.d/indexer b/system/docker/manticore/entrypoint.d/indexer
--- a/system/docker/manticore/entrypoint.d/indexer
+++ b/system/docker/manticore/entrypoint.d/indexer
@@ -16,7 +16,7 @@ IFS=$'\n' read -d '' -r -a MISSING_INDEXES < <(
 ) || true
 
 if [ ${#MISSING_INDEXES[@]} -ne 0 ]; then
-  echo "Building missing indexes" >&2
+  echo "Building missing indexes:" "${MISSING_INDEXES[@]}" >&2
   printf '%s\0' "${MISSING_INDEXES[@]}" | \
     xargs --null --max-args=1 --max-procs=2 --verbose -- \
     indexer --config /etc/sphinxsearch/sphinx.conf
